# EDA

In [71]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pd.set_option('display.max_rows', 25)
pd.set_option('display.max_columns', 20)

data = pd.read_csv('./data/data.csv', delimiter=',')
data.head()

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1,0.035490

In [44]:
desc = data.describe().T
desc

,count,mean,std,min,25%,50%,75%,max
Bankrupt?,6819.0,3.226280e-02,1.767102e-01,0.0,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
ROA(C) before interest and depreciation before interest,6819.0,5.051796e-01,6.068564e-02,0.0,4.765271e-01,5.027056e-01,5.355628e-01,1.000000e+00
ROA(A) before interest and % after tax,6819.0,5.586249e-01,6.562003e-02,0.0,5.355430e-01,5.598016e-01,5.891572e-01,1.000000e+00
ROA(B) before interest and depreciation after tax,6819.0,5.535887e-01,6.159481e-02,0.0,5.272766e-01,5.522780e-01,5.841051e-01,1.000000e+00
Operating Gross Margin,6819.0,6.079480e-01,1.693381e-02,0.0,6.004447e-01,6.059975e-01,6.139142e-01,1.000000e+00
Realized Sales Gross Margin,6819.0,6.079295e-01,1.691607e-02,0.0,6.004338e-01,6.059759e-01,6.138421e-01,1.000000e+00
Operating Profit Rate,6819.0,9.987551e-01,1.301003e-02,0.0,9.989692e-01,9.990222e-01,9.990945e-01,1.000000e+00
Pre-tax net Interest Rate,6819.0,7.971898e-01,1.286899e-02,0.0,7.973859e-01,7.974636e-01,7.975788e-01,1.000000e+00
After-tax net Interest Rate,6819.0,8.090836e-01,1.360065e-02,0.0,8.093116e-01,8.093752e-01,8.094693e-01,1.000000e+00
Non-industry income and expenditure/revenue,6819.0,3.036229e-01,1.116344e-02,0.0,3.034663e-01,3.035255e-01,3.035852e-01,1.000000e+00
Continuous interest rate (after tax),6819.0,7.813814e-01,1.267900e-02,0.0,7.815668e-01,7.816350e-01,7.817354e-01,1.000000e+00
Operating Expense Rate,6819.0,1.995347e+09,3.237684e+09,0.0,1.566874e-04,2.777589e-04,4.145000e+09,9.990000e+09
Research and development expense rate,6819.0,1.950427e+09,2.598292e+09,0.0,1.281880e-04,5.090000e+08,3.450000e+09,9.980000e+09
Cash flow rate,6819.0,4.674312e-01,1.703552e-02,0.0,4.615578e-01,4.650797e-01,4.710039e-01,1.000000e+00
Interest-bearing debt interest rate,6819.0,1.644801e+07,1.082750e+08,0.0,2.030203e-04,3.210321e-04,5.325533e-04,9.900000e+08
Tax rate (A),6819.0,1.150007e-01,1.386675e-01,0.0,0.000000e+00,7.348922e-02,2.058407e-01,1.000000e+00
Net Value Per Share (B),6819.0,1.906606e-01,3.338977e-02,0.0,1.736126e-01,1.844002e-01,1.995702e-01,1.000000e+00
Net Value Per Share (A),6819.0,1.906332e-01,3.347351e-02,0.0,1.736126e-01,1.844002e-01,1.995702e-01,1.000000e+00
Net Value Per Share (C),6819.0,1.906724e-01,3.348014e-02,0.0,1.736758e-01,1.844002e-01,1.996123e-01,1.000000e+00
Persistent EPS in the Last Four Seasons,6819.0,2.288129e-01,3.326261e-02,0.0,2.147112e-01,2.245438e-01,2.388201e-01,1.000000e+00
Cash Flow Per Share,6819.0,3.234819e-01,1.761091e-02,0.0,3.177478e-01,3.224871e-01,3.286235e-01,1.000000e+00
Revenue Per Share (Yuan ¥),6819.0,1.328641e+06,5.170709e+07,0.0,1.563138e-02,2.737571e-02,4.635722e-02,3.020000e+09
Operating Profit Per Share (Yuan ¥),6819.0,1.090907e-01,2.794224e-02,0.0,9.608338e-02,1.042260e-01,1.161550e-01,1.000000e+00
Per Share Net profit before tax (Yuan ¥),6819.0,1.843606e-01,3.318021e-02,0.0,1.703698e-01,1.797093e-01,1.934925e-01,1.000000e+00
Realized Sales Gross Profit Growth Rate,6819.0,2.240785e-02,1.207927e-02,0.0,2.206453e-02,2.210237e-02,2.215315e-02,1.000000e+00
Operating Profit Growth Rate,6819.0,8.479800e-01,1.075248e-02,0.0,8.479841e-01,8.480435e-01,8.481225e-01,1.000000e+00
After-tax Net Profit Growth Rate,6819.0,6.891461e-01,1.385302e-02,0.0,6.892699e-01,6.894385e-01,6.896472e-01,1.000000e+00
Regular Net Profit Growth Rate,6819.0,6.891500e-01,1.391028e-02,0.0,6.892703e-01,6.894386e-01,6.896470e-01,1.000000e+00
Continuous Net Profit Growth Rate,6819.0,2.176390e-01,1.006296e-02,0.0,2.175795e-01,2.175980e-01,2.176215e-01,1.000000e+00
Total Asset Growth Rate,6819.0,5.508097e+09,2.897718e+09,0.0,4.860000e+09,6.400000e+09,7.390000e+09,9.990000e+09
Net Value Growth Rate,6819.0,1.566212e+06,1.141594e+08,0.0,4.409689e-04,4.619555e-04,4.993621e-04,9.330000e+09
Total Asset Return Growth Rate Ratio,6819.0,2.642475e-01,9.634209e-03,0.0,2.637589e-01,2.640495e-01,2.643883e-01,1.000000e+00
Cash Reinvestment %,6819.0,3.796767e-01,2.073657e-02,0.0,3.747485e-01,3.804255e-01,3.867311e-01,1.000000e+00
Current Ratio,6819.0,4.032850e+05,3.330216e+07,0.0,7.555047e-03,1.058717e-02,1.626953e-02,2.750000e+09
Quick Ratio,6819.0,8.376595e+06,2.446847e+08,0.0,4.725903e-03,7.412472e-03,1.224911e-02,9.230000e+09
Interest Expense Ratio,6819.0,6.309910e-01,1.123846e-02,0.0,6.306123e-01,6.306982e-01,6.311253e-01,1.000000e+00
Total debt/Total net worth,6819.0,4.416337e+06,1.684069e+08,0.0,3.007049e-03,5.546284e-03,9.273293e-03,9.940000e+09
Debt ratio %,6819.0,1.131771e-01,5.392031e-02,0.0,7.289053e-02,1.114067e-01,1.488043e-01,1.000000e+00
Net worth/Assets,6819.0,8.868229e-01,5.392031e-02,0.0,8.511957e-01,8.885933e-01,9.271095e-01,1.000000e+00
Long-term fund suitability ratio (A),6819.0,8.782734e-03,2.815293e-02,0.0,5.243684e-03,5.664636e-03,6.847432e-03,1.000000e+00
Borrowing dependency,6819.0,3.746543e-01,1.628616e-02,0.0,3.701678e-01,3.726243e-01,3.762707e-01,1.000000e+00
Contingent liabilities/Net worth,6819.0,5.968277e-03,1.218836e-02,0.0,5.365848e-03,5.365848e-03,5.764356e-03,1.000000e+00
Operating profit/Paid-in capital,6819.0,1.089767e-01,2.778169e-02,0.0,9.610468e-02,1.041331e-01,1.159273e-01,1.000000e+00
Net profit before tax/Paid-in capital,6819.0,1.827150e-01,3.078477e-02,0.0,1.693764e-01,1.784556e-01,1.916070e-01,1.000000e+00
Inventory and accounts receivable/Net value,6819.0,4.024593e-01,1.332408e-02,0.0,3.974027e-01,4.001310e-01,4.045508e-01,1.000000e+00
Total Asset Turnover,6819.0,1.416056e-01,1.011450e-01,0.0,7.646177e-02,1.184408e-01,1.769115e-01,1.000000e+00
Accounts Receivable Turnover,6819.0,1.278971e+07,2.782598e+08,0.0,7.101336e-04,9.678107e-04,1.454759e-03,9.740000e+09
Average Collection Days,6819.0,9.826221e+06,2.563589e+08,0.0,4.386530e-03,6.572537e-03,8.972876e-03,9.730000e+09
Inventory Turnover Rate (times),6819.0,2.149106e+09,3.247967e+09,0.0,1.728256e-04,7.646743e-04,4.620000e+09,9.990000e+09
Fixed Assets Turnover Frequency,6819.0,1.008596e+09,2.477557e+09,0.0,2.330013e-04,5.930942e-04,3.652371e-03,9.990000e+09
Net Worth Turnover Rate (times),6819.0,3.859505e-02,3.668034e-02,0.0,2.177419e-02,2.951613e-02,4.290323e-02,1.000000e+00
Revenue per person,6819.0,2.325854e+06,1.366327e+08,0.0,1.043285e-02,1.861551e-02,3.585477e-02,8.810000e+09
Operating profit per person,6819.0,4.006710e-01,3.272014e-02,0.0,3.924380e-01,3.958979e-01,4.018509e-01,1.000000e+00
Allocation rate per person,6819.0,1.125579e+07,2.945063e+08,0.0,4.120529e-03,7.844373e-03,1.502031e-02,9.570000e+09
Working Capital to Total Assets,6819.0,8.141252e-01,5.905440e-02,0.0,7.743090e-01,8.102752e-01,8.503828e-01,1.000000e+00
Quick Assets/Total Assets,6819.0,4.001318e-01,2.019981e-01,0.0,2.419729e-01,3.864509e-01,5.405937e-01,1.000000e+00
Current Assets/Total Assets,6819.0,5.222734e-01,2.181118e-01,0.0,3.528454e-01,5.148298e-01,6.890507e-01,1.000000e+00
Cash/Total Assets,6819.0,1.240946e-01,1.392506e-01,0.0,3.354322e-02,7.488746e-02,1.610732e-01,1.000000e+00
Quick Assets/Current Liability,6819.0,3.592902e+06,1.716209e+08,0.0,5.239776e-03,7.908898e-03,1.295091e-02,8.820000e+09
Cash/Current Liability,6819.0,3.715999e+07,5.103509e+08,0.0,1.973008e-03,4.903886e-03,1.280557e-02,9.650000e+09
Current Liability to Assets,6819.0,9.067279e-02,5.028986e-02,0.0,5.330128e-02,8.270479e-02,1.195230e-01,1.000000e+00
Operating Funds to Liability,6819.0,3.538280e-01,3.514718e-02,0.0,3.410230e-01,3.485967e-01,3.609149e-01,1.000000e+00
Inventory/Working Capital,6819.0,2.773951e-01,1.046885e-02,0.0,2.770340e-01,2.771777e-01,2.774287e-01,1.000000e+00
Inventory/Current Liability,6819.0,5.580680e+07,5.820516e+08,0.0,3.163148e-03,6.497335e-03,1.114677e-02,9.910000e+09
Current Liabilities/Liability,6819.0,7.615989e-01,2.066768e-01,0.0,6.269808e-01,8.068814e-01,9.420267e-01,1.000000e+00
Working Capital/Equity,6819.0,7.358165e-01,1.167803e-02,0.0,7.336118e-01,7.360127e-01,7.385599e-01,1.000000e+00
Current Liabilities/Equity,6819.0,3.314098e-01,1.348803e-02,0.0,3.280958e-01,3.296851e-01,3.323224e-01,1.000000e+00
Long-term Liability to Current Assets,6819.0,5.416004e+07,5.702706e+08,0.0,0.000000e+00,1.974619e-03,9.005946e-03,9.540000e+09
Retained Earnings to Total Assets,6819.0,9.347328e-01,2.556422e-02,0.0,9.310965e-01,9.376723e-01,9.448113e-01,1.000000e+00
Total income/Total expense,6819.0,2.548946e-03,1.209281e-02,0.0,2.235596e-03,2.336171e-03,2.491851e-03,1.000000e+00
Total expense/Assets,6819.0,2.918410e-02,2.714878e-02,0.0,1.456706e-02,2.267395e-02,3.593014e-02,1.000000e+00
Current Asset Turnover Rate,6819.0,1.195856e+09,2.821161e+09,0.0,1.456236e-04,1.987816e-04,4.525945e-04,1.000000e+10
Quick Asset Turnover Rate,6819.0,2.163735e+09,3.374944e+09,0.0,1.417149e-04,2.247728e-04,4.900000e+09,1.000000e+10
Working capitcal Turnover Rate,6819.0,5.940063e-01,8.959384e-03,0.0,5.939344e-01,5.939628e-01,5.940023e-01,1.000000e+00
Cash Turnover Rate,6819.0,2.471977e+09,2.938623e+09,0.0,2.735337e-04,1.080000e+09,4.510000e+09,1.000000e+10
Cash Flow to Sales,6819.0,6.715308e-01,9.341346e-03,0.0,6.715653e-01,6.715740e-01,6.715866e-01,1.000000e+00
Fixed Assets to Assets,6819.0,1.220121e+06,1.007542e+08,0.0,8.536037e-02,1.968810e-01,3.722000e-01,8.320000e+09
Current Liability to Liability,6819.0,7.615989e-01,2.066768e-01,0.0,6.269808e-01,8.068814e-01,9.420267e-01,1.000000e+00
Current Liability to Equity,6819.0,3.314098e-01,1.348803e-02,0.0,3.280958e-01,3.296851e-01,3.323224e-01,1.000000e+00
Equity to Long-term Liability,6819.0,1.156447e-01,1.952918e-02,0.0,1.109332e-01,1.123400e-01,1.171061e-01,1.000000e+00
Cash Flow to Total Assets,6819.0,6.497306e-01,4.737213e-02,0.0,6.332653e-01,6.453665e-01,6.630619e-01,1.000000e+00
Cash Flow to Liability,6819.0,4.618493e-01,2.994268e-02,0.0,4.571165e-01,4.597501e-01,4.642358e-01,1.000000e+00
CFO to Assets,6819.0,5.934151e-01,5.856055e-02,0.0,5.659869e-01,5.932663e-01,6.247689e-01,1.000000e+00
Cash Flow to Equity,6819.0,3.155824e-01,1.296089e-02,0.0,3.129947e-01,3.149528e-01,3.177072e-01,1.000000e+00
Current Liability to Current Assets,6819.0,3.150637e-02,3.084469e-02,0.0,1.803367e-02,2.759714e-02,3.837462e-02,1.000000e+00
Liability-Assets Flag,6819.0,1.173193e-03,3.423431e-02,0.0,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
Net Income to Total Assets,6819.0,8.077602e-01,4.033219e-02,0.0,7.967498e-01,8.106190e-01,8.264545e-01,1.000000e+00
Total assets to GNP price,6819.0,1.862942e+07,3.764501e+08,0.0,9.036205e-04,2.085213e-03,5.269777e-03,9.820000e+09
No-credit Interval,6819.0,6.239146e-01,1.228955e-02,0.0,6.236363e-01,6.238792e-01,6.241682e-01,1.000000e+00
Gross Profit to Sales,6819.0,6.079463e-01,1.693381e-02,0.0,6.004429e-01,6.059983e-01,6.139133e-01,1.000000e+00
Net Income to Stockholder's Equity,6819.0,8.404021e-01,1.452253e-02,0.0,8.401148e-01,8.411788e-01,8.423570e-01,1.000000e+00
Liability to Equity,6819.0,2.803652e-01,1.446322e-02,0.0,2.769442e-01,2.787776e-01,2.814492e-01,1.000000e+00
Degree of Financial Leverage (DFL),6819.0,2.754112e-02,1.566794e-02,0.0,2.679116e-02,2.680813e-02,2.691318e-02,1.000000e+00
Interest Coverage Ratio (Interest expense to EBIT),6819.0,5.653579e-01,1.321424e-02,0.0,5.651584e-01,5.652519e-01,5.657247e-01,1.000000e+00
Net Income Flag,6819.0,1.000000e+00,0.000000e+00,1.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
Equity to Liability,6819.0,4.757836e-02,5.001372e-02,0.0,2.447669e-02,3.379770e-02,5.283782e-02,1.000000e+00

La maggior parte delle variabili hanno minino 0 e massimo 1 -> assumono valori in [0, 1].
Altre invece non sono scalate, procediamo quindi a scalare queste variabili.
Prima di scalarle, applichiamo un /sigma clipping per il rilevamento di eventuali outliers.

In [67]:
#prendiamo le feature che hanno un valore massimo diverso da 1 -> praticamente il subset non scalato
not_scaled_cols = desc[desc['max'] != 1].index
not_scaled_data = data[not_scaled_cols]
not_scaled_data

,Operating Expense Rate,Research and development expense rate,Interest-bearing debt interest rate,Revenue Per Share (Yuan ¥),Total Asset Growth Rate,Net Value Growth Rate,Current Ratio,Quick Ratio,Total debt/Total net worth,Accounts Receivable Turnover,...,Allocation rate per person,Quick Assets/Current Liability,Cash/Current Liability,Inventory/Current Liability,Long-term Liability to Current Assets,Current Asset Turnover Rate,Quick Asset Turnover Rate,Cash Turnover Rate,Fixed Assets to Assets,Total assets to GNP price
0,1.256969e-04,0.000000e+00,7.250725e-04,0.017560,4.980000e+09,0.000327,0.002259,0.001208,0.021266,0.001814,...,0.037135,0.001997,1.473360e-04,0.001036,2.559237e-02,7.010000e+08,6.550000e+09,4.580000e+08,0.424206,0.009219
1,2.897851e-04,0.000000e+00,6.470647e-04,0.021144,6.110000e+09,0.000443,0.006016,0.004039,0.012502,0.001286,...,0.012335,0.004136,1.383910e-03,0.005210,2.394682e-02,1.065198e-04,7.700000e+09,2.490000e+09,0.468828,0.008323
2,2.361297e-04,2.550000e+07,7.900790e-04,0.005944,7.280000e+09,0.000396,0.011543,0.005348,0.021248,0.001495,...,0.141016,0.006302,5.340000e+09,0.013879,3.715116e-03,1.791094e-03,1.022676e-03,7.610000e+08,0.276179,0.040003
3,1.078888e-04,0.000000e+00,4.490449e-04,0.014368,4.880000e+09,0.000382,0.004194,0.002896,0.009572,0.001966,...,0.021320,0.002961,1.010646e-03,0.003540,2.216520e-02,8.140000e+09,6.050000e+09,2.030000e+09,0.559144,0.003252
4,7.890000e+09,0.000000e+00,6.860686e-04,0.029690,5.510000e+09,0.000439,0.006022,0.003727,0.005150,0.001449,...,0.023988,0.004275,6.804636e-04,0.004869,0.000000e+00,6.680000e+09,5.050000e+09,8.240000e+08,0.309555,0.003878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6814,1.510213e-04,4.500000e+09,1.790179e-04,0.020766,7.070000e+09,0.000450,0.010451,0.005457,0.006655,0.000690,...,0.006312,0.005469,5.071548e-03,0.013212,1.792237e-03,2.294154e-04,1.244230e-04,1.077940e-04,0.400338,0.000466
6815,5.220000e+09,1.440000e+09,2.370237e-04,0.023050,5.220000e+09,0.000445,0.009259,0.006741,0.004623,0.000655,...,0.003401,0.006790,4.727181e-03,0.006730,2.204673e-03,1.517299e-04,1.173396e-04,7.710000e+09,0.096136,0.001959
6816,2.509312e-04,1.039086e-04,0.000000e+00,0.044255,5.990000e+09,0.000435,0.038424,0.035112,0.001392,0.001510,...,0.002774,0.035531,8.821248e-02,0.007810,0.000000e+00,1.762272e-04,1.749713e-04,4.074263e-04,0.055509,0.002840
6817,1.236154e-04,2.510000e+09,2.110211e-04,0.031535,7.250000e+09,0.000529,0.012782,0.007256,0.003816,0.000716,...,0.007489,0.007753,7.133218e-03,0.013334,3.200000e+09,2.135940e-04,1.351937e-04,1.165392e-04,0.246805,0.002837
6818,1.431695e-03,0.000000e+00,5.900000e+08,0.000665,9.350000e+09,0.000519,0.051348,0.040897,0.000461,0.000325,...,0.000963,0.051481,6.667354e-02,0.000000,0.000000e+00,7.863781e-03,8.238471e-03,9.505992e-03,0.005016,0.000707

In [73]:
desc_ns = not_scaled_data.describe()
desc_ns

,Operating Expense Rate,Research and development expense rate,Interest-bearing debt interest rate,Revenue Per Share (Yuan ¥),Total Asset Growth Rate,Net Value Growth Rate,Current Ratio,Quick Ratio,Total debt/Total net worth,Accounts Receivable Turnover,...,Allocation rate per person,Quick Assets/Current Liability,Cash/Current Liability,Inventory/Current Liability,Long-term Liability to Current Assets,Current Asset Turnover Rate,Quick Asset Turnover Rate,Cash Turnover Rate,Fixed Assets to Assets,Total assets to GNP price
count,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,...,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03,6.819000e+03
mean,1.995347e+09,1.950427e+09,1.644801e+07,1.328641e+06,5.508097e+09,1.566212e+06,4.032850e+05,8.376595e+06,4.416337e+06,1.278971e+07,...,1.125579e+07,3.592902e+06,3.715999e+07,5.580680e+07,5.416004e+07,1.195856e+09,2.163735e+09,2.471977e+09,1.220121e+06,1.862942e+07
std,3.237684e+09,2.598292e+09,1.082750e+08,5.170709e+07,2.897718e+09,1.141594e+08,3.330216e+07,2.446847e+08,1.684069e+08,2.782598e+08,...,2.945063e+08,1.716209e+08,5.103509e+08,5.820516e+08,5.702706e+08,2.821161e+09,3.374944e+09,2.938623e+09,1.007542e+08,3.764501e+08
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.566874e-04,1.281880e-04,2.030203e-04,1.563138e-02,4.860000e+09,4.409689e-04,7.555047e-03,4.725903e-03,3.007049e-03,7.101336e-04,...,4.120529e-03,5.239776e-03,1.973008e-03,3.163148e-03,0.000000e+00,1.456236e-04,1.417149e-04,2.735337e-04,8.536037e-02,9.036205e-04
50%,2.777589e-04,5.090000e+08,3.210321e-04,2.737571e-02,6.400000e+09,4.619555e-04,1.058717e-02,7.412472e-03,5.546284e-03,9.678107e-04,...,7.844373e-03,7.908898e-03,4.903886e-03,6.497335e-03,1.974619e-03,1.987816e-04,2.247728e-04,1.080000e+09,1.968810e-01,2.085213e-03
75%,4.145000e+09,3.450000e+09,5.325533e-04,4.635722e-02,7.390000e+09,4.993621e-04,1.626953e-02,1.224911e-02,9.273293e-03,1.454759e-03,...,1.502031e-02,1.295091e-02,1.280557e-02,1.114677e-02,9.005946e-03,4.525945e-04,4.900000e+09,4.510000e+09,3.722000e-01,5.269777e-03
max,9.990000e+09,9.980000e+09,9.900000e+08,3.020000e+09,9.990000e+09,9.330000e+09,2.750000e+09,9.230000e+09,9.940000e+09,9.740000e+09,...,9.570000e+09,8.820000e+09,9.650000e+09,9.910000e+09,9.540000e+09,1.000000e+10,1.000000e+10,1.000000e+10,8.320000e+09,9.820000e+09

In [77]:
mean_max = desc_ns.loc[['mean', 'max'], not_scaled_cols]
mean_max.T

                                               mean           max
Operating Expense Rate                 1.995347e+09  9.990000e+09
Research and development expense rate  1.950427e+09  9.980000e+09
Interest-bearing debt interest rate    1.644801e+07  9.900000e+08
Revenue Per Share (Yuan ¥)             1.328641e+06  3.020000e+09
Total Asset Growth Rate                5.508097e+09  9.990000e+09
Net Value Growth Rate                  1.566212e+06  9.330000e+09
Current Ratio                          4.032850e+05  2.750000e+09
Quick Ratio                            8.376595e+06  9.230000e+09
Total debt/Total net worth             4.416337e+06  9.940000e+09
Accounts Receivable Turnover           1.278971e+07  9.740000e+09
Average Collection Days                9.826221e+06  9.730000e+09
Inventory Turnover Rate (times)        2.149106e+09  9.990000e+09
Fixed Assets Turnover Frequency        1.008596e+09  9.990000e+09
Revenue per person                     2.325854e+06  8.810000e+09
Allocation rate per person             1.125579e+07  9.570000e+09
Quick Assets/Current Liability         3.592902e+06  8.820000e+09
Cash/Current Liability                 3.715999e+07  9.650000e+09
Inventory/Current Liability            5.580680e+07  9.910000e+09
Long-term Liability to Current Assets  5.416004e+07  9.540000e+09
Current Asset Turnover Rate            1.195856e+09  1.000000e+10
Quick Asset Turnover Rate              2.163735e+09  1.000000e+10
Cash Turnover Rate                     2.471977e+09  1.000000e+10
Fixed Assets to Assets                 1.220121e+06  8.320000e+09
Total assets to GNP price              1.862942e+07  9.820000e+09

In [91]:
q1 = desc_ns.loc['25%', not_scaled_cols]
q2 = desc_ns.loc['50%', not_scaled_cols]
q3 = desc_ns.loc['75%', not_scaled_cols]
iqr= q3 - q1
sigma_hat=iqr/1.35

In [93]:
def sigma_clip(df, n_sigma=5):
    df_clean = df.copy()
    
    # Seleziona solo le colonne numeriche
    for col in df_clean.select_dtypes(include=np.number).columns:
        
        # Saltiamo le colonne binarie come 'Bankrupt?' per sicurezza
        if df_clean[col].nunique() <= 2:
            continue
            
        # Rimuoviamo temporaneamente i NaN solo per calcolare i percentili corretti
        valori_validi = df_clean[col].dropna()
        if len(valori_validi) == 0:
            continue # Se la colonna è completamente vuota, passa alla successiva
            
        quartiles = np.percentile(valori_validi, [25, 50, 75])
        median = quartiles[1]
        iqr = quartiles[2] - quartiles[0]
        
        # Se l'IQR è zero, usiamo una stima minima per evitare che sigma_hat sia 0
        if iqr == 0:
            sigma_hat = 1e-6
        else:
            sigma_hat = iqr / 1.349 # 1.349 è più preciso di 1.35
        
        # Calcoliamo i limiti
        lower_limit = median - n_sigma * sigma_hat
        upper_limit = median + n_sigma * sigma_hat
        
        # APPLICHIAMO IL CLIP: Sostituiamo i valori fuori limite senza eliminare le righe!
        df_clean[col] = df_clean[col].clip(lower=lower_limit, upper=upper_limit)
        
    return df_clean

# Adesso puoi lanciarla in totale sicurezza
data_clean = sigma_clip(data)
print(f"Dataset pulito con successo! Righe totali rimaste: {data_clean.shape[0]}")

Dataset pulito con successo! Righe totali rimaste: 6819